services:
  - type: web
    name: Elisben-International-Dashboard-System
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py migrate && python manage.py collectstatic --no-input"
    startCommand: "gunicorn schoolms.wsgi:application"