# Generated by Django 5.2.7 on 2025-10-15 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_academicsession_remove_feerecord_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('last_class', models.CharField(max_length=50)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='alumni_profiles/')),
                ('reason', models.CharField(choices=[('Graduated', 'Graduated'), ('Transferred', 'Transferred'), ('Withdrawn', 'Withdrawn')], max_length=20)),
                ('year_left', models.CharField(max_length=10)),
                ('moved_on', models.DateField(auto_now_add=True)),
                ('original_registration_date', models.DateTimeField()),
                ('current_institution', models.CharField(blank=True, max_length=200, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('moved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.admin')),
            ],
            options={
                'verbose_name_plural': 'Alumni',
            },
        ),
    ]
