# Generated by Django 5.2.7 on 2025-10-17 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_student_email_alter_student_phone_alumni'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(default='Elisben International College', max_length=200)),
                ('school_motto', models.CharField(default='Excellence in Education', max_length=200)),
                ('address', models.TextField(default='Surulere Quarters, Oke Osum Ikere Ekiti, Nigeria')),
                ('phone', models.CharField(default='+234 803 634 3681', max_length=50)),
                ('email', models.EmailField(default='admin@elisbencollege.com', max_length=254)),
                ('website', models.URLField(blank=True, null=True)),
                ('school_logo', models.ImageField(blank=True, null=True, upload_to='school_logo/')),
            ],
            options={
                'verbose_name': 'School Settings',
                'verbose_name_plural': 'School Settings',
            },
        ),
        migrations.RenameField(
            model_name='resultsummary',
            old_name='total_score',
            new_name='score_gained',
        ),
        migrations.RenameField(
            model_name='subjectgrade',
            old_name='position',
            new_name='position_in_subject',
        ),
        migrations.AddField(
            model_name='resultsummary',
            name='hos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hos_remarks', to='accounts.teacher'),
        ),
        migrations.AddField(
            model_name='resultsummary',
            name='hos_remark',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resultsummary',
            name='promotion_status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='resultsummary',
            name='pta_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='resultsummary',
            name='resumption_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resultsummary',
            name='vacation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subjectgrade',
            name='class_average',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='resultsummary',
            name='position_in_class',
            field=models.CharField(blank=True, default=0, max_length=20),
            preserve_default=False,
        ),
    ]
