# Generated by Django 5.2.7 on 2025-10-22 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_schoolsettings_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolsettings',
            name='school_logo',
        ),
    ]
