# Generated by Django 5.2.7 on 2025-11-11 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_exam_publishing'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=100)),
                ('academic_year', models.CharField(max_length=50)),
                ('class_name', models.CharField(max_length=50)),
                ('total_subjects', models.IntegerField(default=0)),
                ('score_gained', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('average_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('position_in_class', models.CharField(blank=True, max_length=20)),
                ('status_promotion', models.CharField(blank=True, max_length=50)),
                ('times_school_opened', models.IntegerField(default=0)),
                ('times_present', models.IntegerField(default=0)),
                ('times_absent', models.IntegerField(default=0)),
                ('vacation_date', models.DateField(blank=True, null=True)),
                ('resumption_date', models.DateField(blank=True, null=True)),
                ('next_term_pta_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('next_term_school_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('affective_punctuality', models.CharField(blank=True, max_length=10)),
                ('affective_neatness', models.CharField(blank=True, max_length=10)),
                ('affective_politeness', models.CharField(blank=True, max_length=10)),
                ('affective_honesty', models.CharField(blank=True, max_length=10)),
                ('affective_relationship', models.CharField(blank=True, max_length=10)),
                ('affective_self_control', models.CharField(blank=True, max_length=10)),
                ('affective_attentiveness', models.CharField(blank=True, max_length=10)),
                ('psycho_handwriting', models.CharField(blank=True, max_length=10)),
                ('psycho_sports', models.CharField(blank=True, max_length=10)),
                ('psycho_handling_tools', models.CharField(blank=True, max_length=10)),
                ('psycho_verbal_fluency', models.CharField(blank=True, max_length=10)),
                ('psycho_games', models.CharField(blank=True, max_length=10)),
                ('psycho_drawing', models.CharField(blank=True, max_length=10)),
                ('class_teacher_comment', models.TextField(blank=True)),
                ('principal_comment', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent_to_principal', 'Sent to Principal'), ('with_principal', 'With Principal'), ('sent_to_admin', 'Sent to Admin'), ('with_admin', 'With Admin'), ('published', 'Published')], default='draft', max_length=30)),
                ('sent_to_principal_at', models.DateTimeField(blank=True, null=True)),
                ('sent_to_admin_at', models.DateTimeField(blank=True, null=True)),
                ('has_stamp', models.BooleanField(default=False)),
                ('stamped_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_teacher_results', to='accounts.teacher')),
                ('principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.principal')),
                ('stamped_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.admin')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.student')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('student', 'term', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='ResultActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('subject_result_entered', 'Subject Result Entered'), ('result_collated', 'Result Collated by Class Teacher'), ('sent_to_principal', 'Sent to Principal'), ('principal_commented', 'Principal Added Comment'), ('sent_to_admin', 'Sent to Admin'), ('admin_edited', 'Admin Edited Result'), ('stamp_added', 'Stamp Added'), ('result_published', 'Result Published')], max_length=50)),
                ('description', models.TextField()),
                ('performed_by_type', models.CharField(max_length=20)),
                ('performed_by_name', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('student_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.studentresult')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PublishedResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.CharField(max_length=20, unique=True)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.CharField(max_length=50)),
                ('term', models.CharField(max_length=100)),
                ('class_name', models.CharField(max_length=50)),
                ('published_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.admin')),
                ('result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.studentresult')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=200)),
                ('term', models.CharField(max_length=100)),
                ('academic_year', models.CharField(max_length=50)),
                ('test_a', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('test_b', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('test_c', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('avg_1', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('exam', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('avg_2', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('ltcum', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('atcum', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('grade', models.CharField(blank=True, max_length=2)),
                ('position_ranking', models.IntegerField(blank=True, null=True)),
                ('class_average', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('grade_remark', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.teacher')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.student')),
            ],
            options={
                'unique_together': {('student', 'subject_name', 'term', 'academic_year')},
            },
        ),
    ]
