# Generated by Django 5.2.7 on 2025-12-06 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_studentresult_resultactivitylog_publishedresult_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subjectresult',
            old_name='atcum',
            new_name='cum',
        ),
        migrations.AlterField(
            model_name='subjectresult',
            name='ltcum',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
    ]
