# Generated by Django 5.2.7 on 2025-12-06 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_rename_atcum_subjectresult_cum_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_type', models.CharField(max_length=20)),
                ('notification_type', models.CharField(choices=[('new_result', 'New Result Submitted'), ('result_updated', 'Result Updated'), ('result_resent', 'Result Resent')], max_length=20)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_notifications', to=settings.AUTH_USER_MODEL)),
                ('student_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.studentresult')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
