# Generated by Django 5.2.7 on 2026-01-08 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_resultnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.CharField(blank=True, choices=[('', 'N/A (Junior Classes)'), ('Science', 'Science Department'), ('Art', 'Art Department'), ('Commercial', 'Commercial Department')], default='', help_text='Required for SS1, SS2, SS3 students only', max_length=20),
        ),
    ]
