# Generated by Django 5.2.7 on 2026-02-24 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_student_department'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='examsubmission',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='exam',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='examsubmission',
            name='exam_version',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='examsubmission',
            unique_together={('student', 'exam', 'exam_version')},
        ),
    ]
