# Generated by Django 5.2.7 on 2026-09-10 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_examsubmission_unique_together_exam_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishedresult',
            name='published_by_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_results', to='accounts.principal'),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='stamped_by_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stamped_results', to='accounts.principal'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('student_registered', 'Student Registered'), ('teacher_registered', 'Teacher Registered'), ('student_deleted', 'Student Deleted'), ('teacher_deleted', 'Teacher Deleted'), ('exam_created', 'Exam Created'), ('exam_edited', 'Exam Edited'), ('exam_deleted', 'Exam Deleted'), ('exam_submitted', 'Exam Submitted'), ('attendance_marked', 'Attendance Marked'), ('fee_recorded', 'Fee Recorded'), ('grades_entered', 'Grades Entered'), ('result_generated', 'Result Generated'), ('book_added', 'Book Added'), ('book_borrowed', 'Book Borrowed'), ('book_returned', 'Book Returned'), ('admin_id_changed', 'Admin ID Changed')], max_length=50),
        ),
        migrations.AlterField(
            model_name='publishedresult',
            name='published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.admin'),
        ),
    ]
