# Generated by Django 5.2.7 on 2026-09-12 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_publishedresult_published_by_principal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiblingDiscountRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(max_length=20, unique=True)),
                ('fee_type', models.CharField(max_length=100)),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('Bank Transfer', 'Bank Transfer'), ('Card', 'Card')], max_length=50)),
                ('payment_date', models.DateField()),
                ('total_fee_before_discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_fee_after_discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discount_records', to='accounts.bursar')),
                ('created_by_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discount_records', to='accounts.admin')),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.term')),
            ],
        ),
        migrations.CreateModel(
            name='SiblingDiscountEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_before_discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fee_after_discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_entries', to='accounts.student')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='accounts.siblingdiscountrecord')),
            ],
        ),
        migrations.AddField(
            model_name='feerecord',
            name='sibling_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_records', to='accounts.siblingdiscountrecord'),
        ),
    ]
