# Generated by Django 5.2.7 on 2026-09-12 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_siblingdiscountrecord_siblingdiscountentry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolsettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='school_logo/'),
        ),
        migrations.CreateModel(
            name='NonTeachingStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('role_title', models.CharField(blank=True, max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='staff_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_non_teaching_staff', to='accounts.admin')),
                ('registered_by_principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_non_teaching_staff', to='accounts.principal')),
            ],
        ),
        migrations.CreateModel(
            name='IDCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holder_type', models.CharField(choices=[('student', 'Student'), ('teaching_staff', 'Teaching Staff'), ('non_teaching_staff', 'Non-Teaching Staff'), ('principal', 'Principal'), ('admin', 'Admin')], max_length=30)),
                ('full_name', models.CharField(max_length=200)),
                ('id_number', models.CharField(max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('role_title', models.CharField(blank=True, max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='id_cards/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_cards', to='accounts.admin')),
                ('generated_by_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_id_cards', to='accounts.admin')),
                ('generated_by_principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_id_cards', to='accounts.principal')),
                ('principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_cards', to='accounts.principal')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_cards', to='accounts.student')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_cards', to='accounts.teacher')),
                ('non_teaching_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_cards', to='accounts.nonteachingstaff')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
